version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/j-dumbell/splendid
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...