version: '3'
services:
  server:
    build:
      context: go/
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  client:
    build:
      context: client/
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - server
    environment:
      - REACT_APP_API_HOST=localhost:8080
    stdin_open: true

  db:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
