version: 2.1

orbs:
  heroku: circleci/heroku@1.2.2

jobs:
  build-and-test-server:
    docker:
      - image: circleci/golang:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: test
          command: |
            cd server && go test ./...
      - run:
          name: build
          command: |
            cd server && go build main.go

  build-and-test-client:
    docker:
      - image: circleci/node:stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - client_deps-{{ checksum "client/package.json" }}
      - run:
          name: install
          command: |
            cd client && yarn install
      - save_cache:
          key: client_deps-{{ checksum "client/package.json" }}
          paths:
            - /client/node_modules
      - run:
          name: test
          command: |
            cd client && yarn test
      - run:
          name: build
          command: |
            cd client && yarn build

  deploy-heroku:
    machine:
      image: ubuntu-1604:201903-01
    parameters:
      app-name:
        description: The Heroku app name.
        type: string
    working_directory: ~/repo
    steps:
      - heroku/install
      - heroku/check-authentication
      - checkout
      - run:
          name: Login to Heroku Docker image registry
          command: heroku container:login
      - run:
          name: Build & push image
          command: |
            cd server &&
            heroku container:push web -a splendid-server
      - run:
          name: Deploy image
          command: heroku container:release web -a splendid-server

workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - build-and-test-server:
          filters:
            branches:
              ignore: master
      - deploy-heroku:
          app-name: splendid-server
          requires:
            - build-and-test-server
#          filters:
#            branches:
#              only: master

      - build-and-test-client:
          filters:
            branches:
              ignore: master
      - deploy-heroku:
          app-name: splendid-client
          requires:
            - build-and-test-client
#          filters:
#            branches:
#              only: master

