version: 2.1

#orbs:
#  heroku: circleci/heroku@1.2.2

jobs:
  build-and-test-server:
    docker:
      - image: circleci/golang:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: test
          command: |
            cd server && go test ./...
      - run:
          name: build
          command: |
            cd server && go build main.go

  build-and-test-client:
    docker:
      - image: circleci/node:stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - client_deps-{{ checksum "client/package.json" }}
      - run:
          name: install
          command: |
            cd client && yarn install
      - save_cache:
          key: client_deps-{{ checksum "client/package.json" }}
          paths:
            - /client/node_modules
      - run:
          name: test
          command: |
            cd client && yarn test
      - run:
          name: build
          command: |
            cd client && yarn build

  deploy-server:
    docker:
      - image: cimg/base:2020.01
    working_directory: ~/repo
    environment:
      HEROKU_API_KEY: $HEROKU_SERVER_API_KEY
    steps:
      - run:
          name: Install Heroku CLI
          command: |
            (printf 'y' | sudo apt update)
            sudo apt install snapd
            sudo snap install --classic heroku
      - checkout
      - run:
          name: Heroku docker repo login
          command: 'heroku container:login'
      - run:
          name: Build & push image
          command: cd server && heroku container:push -a splendid-server
      - run:
          name: Deploy image
          command: heroku container:release -a splendid-server

workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - build-and-test-server
      - deploy-server:
          requires:
            - build-and-test-server
#          filters:
#            branches:
#              only: master
      - build-and-test-client

