version: 2.1

jobs:
  build-and-test-server:
    docker:
      - image: circleci/golang:latest
    working_directory: ~/repo
    steps:
      - checkout
      #Add tests here when we have some
      - run:
          name: build
          command: |
            cd server && \
            go build cmd/main.go


  build-and-test-client:
    docker:
      - image: circleci/node:stretch
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo/client
      #Add tests here when we have some
      - run:
          name: install
          command: |
            yarn install
      - run:
          name: test
          command: |
            pwd
            yarn test
      - run:
          name: build
          command: |
            yarn build

workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - build-and-test-server
      - build-and-test-client
