version: 2.1

jobs:
  build-and-test-server:
    docker:
      - image: circleci/golang:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: test
          command: |
            cd server && go test ./...
      - run:
          name: build
          command: |
            cd server && go build main.go

  build-and-test-client:
    docker:
      - image: circleci/node:stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - client_deps-{{ checksum "client/package.json" }}
      - run:
          name: install
          command: |
            cd client && yarn install
      - save_cache:
          key: client_deps-{{ checksum "client/package.json" }}
          paths:
            - /client/node_modules
      - run:
          name: test
          command: |
            cd client && yarn test
      - run:
          name: build
          command: |
            cd client && yarn build

workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - build-and-test-server
      - build-and-test-client

