version: 2.1

jobs:
  build-and-test-server:
    docker:
      - image: circleci/golang:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: tree hash
          command: |
            git rev-parse HEAD:server | tee /tmp/server.hash
      - restore_cache:
          keys:
            - v1-tree-{{ checksum "/tmp/server.hash" }}
      - run:
          name: test
          command: |
            [ -f /tmp/success.txt ] && echo "skipping" ||
            (cd server && go test ./...)

      - run:
          name: build
          command: |
            cat /tmp/success.txt && \
            echo "Skipping" ||
            cd server && \
            go build main.go
      - run:
          name: write success
          command: touch /tmp/success.txt
      - save_cache:
          key: v1-tree-{{ checksum "/tmp/server.hash" }}
          paths:
            - /tmp/success.txt


  build-and-test-client:
    docker:
      - image: circleci/node:stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install
          command: |
            cd client && \
            yarn install
      - run:
          name: test
          command: |
            cd client && \
            yarn test
      - run:
          name: build
          command: |
            cd client && \
            yarn build

workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - build-and-test-server
      - build-and-test-client

